### ISSUE TITLE
The notation in the below diagram seems wrong and you might consider changing it.

### ISSUE THREAD

**Issue by aditichadha1310** [AY2223S2-CS2113-T12-2/tp#150]
The green solid and hollow dots should be replaced with relevant "+" and "-" signs.
You should also use the colon symbol ":" in front of the Class names. 

![image](https://user-images.githubusercontent.com/70324480/228740472-7f7265f8-0468-43ab-8334-98c1ee0c4914.png)

**Comment by typingpanda** [comment]
Noted, changed to meet diagram standards!
