### ISSUE TITLE
[PE-D][Tester C] Invalid range format not being highlighted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T12-2/tp#158]
![Screenshot 2023-03-31 161232.png](https://raw.githubusercontent.com/khooyourun/ped/main/files/0bfce5c7-618d-4af1-b2f1-a8ac9d0f8135.png)

In PC Builder mode when no flag is given in the list command, the program simply ignores it without highlighting the missing criteria. User might end up wondering why their desired outputs are not showing up.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: khooyourun/ped#1

**Comment by Magmanat** [comment]
State in the user guide that the recognised flags will be in the "following criteria", any other flags you have typed that are not recognised will not be highlighted
