### ISSUE TITLE
[PE-D][Tester B] Budget feature not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T12-2/tp#159]
![image.png](https://raw.githubusercontent.com/euzhengxi/ped/main/files/f3b2ddbd-caa8-4cc8-b4d4-1bf2f9a60f6b.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: euzhengxi/ped#1

**Comment by Magmanat** [comment]
Also stated many times in previous issue, state specifically in the user guide
