### ISSUE TITLE
[PE-D][Tester B] select feature is not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-2/tp#168]
![image.png](https://raw.githubusercontent.com/euzhengxi/ped/main/files/50768d89-a213-444d-8531-2a517213cf60.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: euzhengxi/ped#5

**Comment by Magmanat** [comment]
this is the pcviewer, state in user guide
