### ISSUE TITLE
[PE-D][Tester D] Add Infinite Budget 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-2/tp#181]
Can perhaps add an option for infinite budget such as the pre-built ones shown at the start

![image.png](https://raw.githubusercontent.com/miahjerry/ped/main/files/1ff83a2d-b353-4d3a-8176-dbe6a0fbadaa.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: miahjerry/ped#7

**Comment by Magmanat** [comment]
as stated in a previous issue we will solve this
