### ISSUE TITLE
[PE-D][Tester B] help command is not listed in the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-2/tp#186]
![image.png](https://raw.githubusercontent.com/euzhengxi/ped/main/files/0401e36a-809a-451a-9b22-6371d3ce5bd2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: euzhengxi/ped#10

**Comment by Magmanat** [comment]
Add help command into user guide, and make it more formatted for easy viewer access

**Comment by Reynold-SL** [comment]
Add help command under common commands in User Guide
![image](https://user-images.githubusercontent.com/88631870/229296196-2efe4561-5729-47f7-a7bb-e45963f7f7a1.png)
