### ISSUE TITLE
[PE-D][Tester D] Incorrect Use Of Punctuation In Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-2/tp#188]
Small error in punctuation. The comma should not be there after the exclamation mark

![image.png](https://raw.githubusercontent.com/miahjerry/ped/main/files/74db1727-73fb-41dd-9f8f-4da204b854ae.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: miahjerry/ped#9

**Comment by Magmanat** [comment]
Solve the punctuation in code
